Fix zip deflate
NOTE: OpenPGP ZIP compression is a raw DEFLATE stream, without zlib
headers.

Fixed an undefined reference to `fake_zip_deflate`, presumably the
function had a typo in the name. Added a way to specify the compression
algo in `burn` API so it's available to the end users and we can also
test it end to end. Added roundtrip tests.